# Generated by Django 5.1.6 on 2025-03-02 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_width', models.IntegerField()),
                ('pants_width', models.IntegerField()),
                ('shoulder_width', models.IntegerField()),
                ('stein_width', models.IntegerField()),
                ('stein_radius', models.IntegerField()),
                ('side_hight', models.IntegerField()),
                ('throat_radius', models.IntegerField()),
                ('pants_radius', models.IntegerField()),
                ('stein_model', models.CharField(max_length=255)),
                ('collar_model', models.CharField(max_length=255)),
                ('customer_size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
